environment:
  matrix:
    - platform: x86
      PHP_VERSION: '7.1.6'
      VC_VERSION: '14'
      PREFER_LOWEST: 

matrix:
  fast_finish: true

init:
  - set PATH=C:\tools;C:\tools\php-%PHP_VERSION%;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\tools\gettext\bin;%PATH%
  - set MYSQL_PWD=Password12!

clone_depth: 50

cache:
  - C:\tools\downloads -> .appveyor.yml
  - '%LOCALAPPDATA%\Composer\files'

services:
  - mysql

install:
  - if not exist C:\tools mkdir C:\tools
  - if not exist C:\tools\downloads mkdir C:\tools\downloads
  - cd /D C:\tools\downloads
  - set PHP_ZIP=php-%PHP_VERSION%-Win32-VC%VC_VERSION%-%PLATFORM%.zip
  - if not exist %PHP_ZIP% (appveyor DownloadFile http://windows.php.net/downloads/releases/archives/%PHP_ZIP% || exit 0)
  - if not exist %PHP_ZIP% (appveyor DownloadFile http://windows.php.net/downloads/releases/%PHP_ZIP% || exit 0)
  - if not exist %PHP_ZIP% appveyor DownloadFile http://windows.php.net/downloads/releases/qa/%PHP_ZIP%
  - set GETTEXT_ZIP=gettext0.19.8.1-iconv1.14-shared-32.zip
  - if not exist %GETTEXT_ZIP% appveyor DownloadFile https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.8.1-v1.14/%GETTEXT_ZIP%
  - if not exist composer.phar appveyor DownloadFile https://getcomposer.org/download/1.4.2/composer.phar
  - cd /D C:\tools
  - if not exist php-%PHP_VERSION% mkdir php-%PHP_VERSION%
  - cd /D C:\tools\php-%PHP_VERSION%
  - if not exist php-installed.txt 7z x -bd -o. -y -- ..\downloads\%PHP_ZIP% >NUL
  - if not exist php-installed.txt copy /Y php.ini-development php.ini
  - if not exist php-installed.txt echo date.timezone="UTC" >> php.ini
  - if not exist php-installed.txt echo extension_dir=ext >> php.ini
  - if not exist php-installed.txt echo extension=php_mbstring.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_bz2.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_mysqli.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_curl.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_gd2.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_intl.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_pdo_mysql.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_xsl.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_fileinfo.dll >> php.ini
  - if not exist php-installed.txt echo extension=php_openssl >> php.ini
  - if not exist php-installed.txt echo zend.assertions=1 >> php.ini
  - if not exist php-installed.txt echo assert.exception=On >> php.ini
  - if not exist php-installed.txt type nul > php-installed.txt
  - cd /D C:\tools
  - if not exist composer.bat echo @php %%~dp0downloads\composer.phar %%* > composer.bat
  - cd /D C:\tools
  - if not exist gettext mkdir gettext
  - cd /D C:\tools\gettext
  - if not exist bin\msgen.exe 7z x -bd -o. -y -- ..\downloads\%GETTEXT_ZIP% >NUL
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - composer install --no-progress --no-suggest --optimize-autoloader --no-ansi --no-interaction %PREFER_LOWEST%

build: off

test_script:
  - mysql --user=root -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY'"
  - mysql --user=root -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY '';" || exit 0
  - mysql --user=root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION; FLUSH PRIVILEGES;"
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=true
  - composer test

deploy: off
