language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1
    - PREFER_LOWEST=""

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: ACTION="php_codestyle"
    - php: 7.1
      env: PREFER_LOWEST="--prefer-lowest"
    - language: node_js
      dist: trusty
      node_js: lts/*
      env: ACTION="js_check"
  allow_failures:
    - php: nightly

before_script:
  - |
    set -o errexit
    case $ACTION in
      js_check)
        travis_retry npm install yarn -g
        travis_retry yarn global add grunt
        cd build
        travis_retry yarn
        ;;
      *)
        if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then
          cat tests/travis.hhvm.ini >> /etc/hhvm/php.ini
        else
          phpenv config-add tests/travis.php.ini
          phpenv config-rm xdebug.ini || true
        fi
        travis_retry composer update --no-suggest --no-interaction $PREFER_LOWEST # Run once to install magento's composer merger
        travis_retry composer update --no-suggest --no-interaction $PREFER_LOWEST # Run twice to install merged dependencies
        ;;
    esac

script:
  - |
    set -o errexit
    case $ACTION in
      php_codestyle)
        composer phpcs
        ;;
      js_check)
        grunt js:check
        ;;
      *)
        composer test
        ;;
    esac

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - build/node_modules

notifications:
  email: false
