language: php
sudo: false

env:
  - COMPOSER_DISABLE_XDEBUG_WARN=1

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then cat tests/travis.hhvm.ini >> /etc/hhvm/php.ini; else phpenv config-add tests/travis.php.ini; fi
  - travis_retry composer install --no-interaction
  - mysql -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY'"
  - phpunit --version

script: phpunit

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  email: false
