language: php
sudo: false
dist: precise

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1
    - PREFER_LOWEST=""

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: CODESTYLE="yes"
    - php: 7.1
      env: PREFER_LOWEST="--prefer-lowest"
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then cat tests/travis.hhvm.ini >> /etc/hhvm/php.ini; else phpenv config-add tests/travis.php.ini; fi
  - if [[ $CODESTYLE != "yes" ]]; then travis_retry composer update --no-suggest --no-interaction $PREFER_LOWEST; fi # Run once to install magento's composer merger
  - if [[ $CODESTYLE != "yes" ]]; then travis_retry composer update --no-suggest --no-interaction $PREFER_LOWEST; fi # Run twice to install merged dependencies
  - if [[ $CODESTYLE != "yes" ]]; then mysql -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY'"; fi
  - if [[ $CODESTYLE != "yes" ]]; phpunit --version; fi
  - if [[ $CODESTYLE = "yes" ]]; phpenv config-rm xdebug.ini; fi

script:
  # Run PHPUnit if we're not checking code style, otherwise run phpcs
  - if [[ $CODESTYLE != "yes" ]]; then composer test; else composer phpcs; fi
cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
