language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "short_open_tag = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - cd web/concrete
  - travis_retry composer install --no-interaction
  - travis_retry composer require "squizlabs/php_codesniffer" --no-interaction
  - cd ../../
  - phpunit --version

script:
  - ./web/concrete/vendor/bin/phpcs --standard=psr2 web/concrete/dispatcher.php `git diff --name-only HEAD`
  - cd tests && phpunit

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  email: false
